### ISSUE TITLE
Chat window logic

### ISSUE THREAD

**Issue by gurinder4seconds** [LogMeIn-BoldChat/Html-Chat-Sdk#13]
When you have started a chat with a rep. 

If you minimise the window to navigate to another part of the site, each new page load automatically opens up the chat window rather than waiting for the user to maximise the chat window again.

The chat window should respect the choice of the customer when it comes to the showing the window.

**Comment by boldwade** [comment]
Hi, that's a great feature request! I'll look at implementing something in the near future. Thanks!
