### ISSUE TITLE
Chat Window Start Chat

### ISSUE THREAD

**Issue by gurinder4seconds** [LogMeIn-BoldChat/Html-Chat-Sdk#14]
On starting a chat the form that asks for user information has asterisks next to each title.

ie. Name *

However there is no accompanying text explaining what the asterisks actually mean.

**Comment by boldwade** [comment]
I believe the asterisk is to indicate a required field. 
This would easily accomplished on your end in the view-manager and/or the themed template file. It is up to you. Just keep in mind that you may implement a chat window without required fields, at some point. In that case, you wouldn't want the asterisk to be a static element. Just something to be aware of.
