### ISSUE TITLE
Replace entire chat window with feedback form on chat complete

### ISSUE THREAD

**Issue by tydanielson** [LogMeIn-BoldChat/Html-Chat-Sdk#5]
I am trying to get the feedback form to replace an entire chat window once a chat has been completed.  Currently the bc-view-manager adds the form as a message to the chat as a system chat.  So is there a way that I can either setup my index.html to have this feedback form be it's own page like the initial form?

**Comment by boldwade** [comment]
Hi Ty, as I understand you just want this particular (feedback) form of yours, which I suppose is wrapped in a container (perhaps a div or whatever) and you want to display that on the end of a chat? Is this correct?

**Comment by tydanielson** [comment]
So yes, I believe this is the usual feedback section.  Right now it is displayed and works, but is shown as a "System" message which is just like any other chat message.  Without adding in everything in the form this is the code that is displayed.

```
<div class="bc-msg-wrap-sys">
       <div class="bc-msg-txt bc-msg-txt-sys" id="bc-form-container">
             <form class="bc-form">
                   <div class="bc-input-container bc-form-intro"></div>
             </form>
       </div>
</div>
```

My problem is that I need this to be the whole page and not just another message in the chat.  Is there an easy way to do this so that its filling the form in an outer element that may wrap the whole window?

**Comment by tydanielson** [comment]
Nevermind regarding the above... I ultimately created a `hideMessages` method and overwrote the `_processChatEndData` method in the session to call it.
