### ISSUE TITLE
Index.html api documentation for classes and id's to use for data

### ISSUE THREAD

**Issue by tydanielson** [LogMeIn-BoldChat/Html-Chat-Sdk#6]
It would be really nice to know which html id's and css classes go where on the html and what they do.  It took me a while to search through the `bc-view-manager.js` to find out that if I wanted to add the name of the person chatting all I had to do was add a `div` with the class `bc-msg-txt`.  It wasn't on the initial index.html of the chat theme i started with (Hubris).

**Comment by boldwade** [comment]
We do have some detail information on the help page, but honestly it's hard to know what we're missing at the time we create the document. When you're working on the code at the time, everything makes sense. When you go back to it later or you've never seen it before, not so much. :) 
I would love to hear other issues you run into that we can address as well!
